install.packages("DT")
install.packages("knitr")
install.packages("leaflet")
install.packages("rmarkdown")
install.packages("xaringan")
install.packages("xaringanthemer")
# remotes::install_github('rstudio/rmarkdown')
# install_version("rmarkdown", version = "2.10")